name: annotation-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.1
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.2.25
  - certifi=2026.2.25
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - dnspython=2.8.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.1
  - fastapi=0.133.1
  - fastapi-cli=0.0.23
  - fastapi-core=0.133.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - libcxx=22.1.0
  - libexpat=2.7.4
  - libffi=3.5.2
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libsqlite=3.51.2
  - libuv=1.51.0
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=26.0
  - pip=26.0.1
  - pluggy=1.6.0
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.13.1
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.13.12
  - python-dotenv=1.2.1
  - python-json-logger=2.0.7
  - python-multipart=0.0.22
  - python_abi=3.13
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - rich=14.3.3
  - rich-toolkit=0.19.7
  - ruff=0.15.2
  - shellingham=1.5.4
  - sniffio=1.3.1
  - starlette=0.52.1
  - tk=8.6.13
  - tomli=2.4.0
  - typer=0.24.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - uvicorn=0.41.0
  - uvicorn-standard=0.41.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - websockets=16.0
  - yaml=0.2.5
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/annotation-engine
